version: '3'
services:
  bootstrap:
    image: mygeth:latest
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2024M   
    hostname: bootstrap
    entrypoint: /root/start_bootstrap.sh
    command: '--datadir=~/.ethereum/devchain --verbosity 2 --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3,admin" --allow-insecure-unlock --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./geth/files/password:/root/files/password:ro
      - ./geth/deployed_contract:/root/deployed_contract/:rw
      - ./geth/shared:/root/shared/:rw
      - ./geth/templates/:/root/templates/:ro
      - ./geth/files/genesis.json:/root/files/genesis.json:ro
      - ./geth/files/genesis_poa.json:/root/files/genesis_poa.json:ro
      - ./geth/files/keystore:/root/.ethereum/devchain/keystore:rw     
#      - ./dag/:/root/.ethash/:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8555:8555"
      - "8545:8545"
  eth:
    image: mygeth:latest
    deploy:
      #replicas: 20
      resources:
        limits:
          cpus: '1.0'
          memory: 1400M 
    entrypoint: /root/start.sh
    depends_on:
     - bootstrap
    volumes:
      - ./geth/files/password:/root/files/password:ro
      - ./geth/deployed_contract/:/root/deployed_contract/:ro
      - ./geth/shared:/root/shared/:ro
      - ./geth/templates/:/root/templates/:ro
      - ./geth/files/genesis.json:/root/files/genesis.json:ro
      - ./geth/files/genesis_poa.json:/root/files/genesis_poa.json:ro	
    #  - ./geth/files/keystore:/root/.ethereum/devchain/keystore:rw      
#      - ./dag/:/root/.ethash/:ro
# If I get an error with later versions of geth, add the allow-insecure-unlock flag again
    command: '--datadir=~/.ethereum/devchain --verbosity 2 --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --rpcapi "db,personal,eth,net,web3,admin" --allow-insecure-unlock --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0" '
